/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShortNotesRouteImport } from './routes/short-notes'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as QnsBankRouteImport } from './routes/qns-bank'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MockTestRouteImport } from './routes/mock-test'
import { Route as McqPracticeRouteImport } from './routes/mcq-practice'
import { Route as FlashCardsRouteImport } from './routes/flash-cards'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomExamRouteImport } from './routes/custom-exam'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminShortNotesRouteImport } from './routes/admin.short-notes'
import { Route as AdminQuizRouteImport } from './routes/admin.quiz'
import { Route as AdminQuestionBankRouteImport } from './routes/admin.question-bank'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMockTestRouteImport } from './routes/admin.mock-test'
import { Route as AdminMcqRouteImport } from './routes/admin.mcq'
import { Route as AdminFlashCardsRouteImport } from './routes/admin.flash-cards'
import { Route as AdminClassesRouteImport } from './routes/admin.classes'

const ShortNotesRoute = ShortNotesRouteImport.update({
  id: '/short-notes',
  path: '/short-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const QnsBankRoute = QnsBankRouteImport.update({
  id: '/qns-bank',
  path: '/qns-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestRoute = MockTestRouteImport.update({
  id: '/mock-test',
  path: '/mock-test',
  getParentRoute: () => rootRouteImport,
} as any)
const McqPracticeRoute = McqPracticeRouteImport.update({
  id: '/mcq-practice',
  path: '/mcq-practice',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashCardsRoute = FlashCardsRouteImport.update({
  id: '/flash-cards',
  path: '/flash-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomExamRoute = CustomExamRouteImport.update({
  id: '/custom-exam',
  path: '/custom-exam',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShortNotesRoute = AdminShortNotesRouteImport.update({
  id: '/short-notes',
  path: '/short-notes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuizRoute = AdminQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionBankRoute = AdminQuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMockTestRoute = AdminMockTestRouteImport.update({
  id: '/mock-test',
  path: '/mock-test',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMcqRoute = AdminMcqRouteImport.update({
  id: '/mcq',
  path: '/mcq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFlashCardsRoute = AdminFlashCardsRouteImport.update({
  id: '/flash-cards',
  path: '/flash-cards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/classes': typeof ClassesRoute
  '/custom-exam': typeof CustomExamRoute
  '/dashboard': typeof DashboardRoute
  '/flash-cards': typeof FlashCardsRoute
  '/mcq-practice': typeof McqPracticeRoute
  '/mock-test': typeof MockTestRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/qns-bank': typeof QnsBankRoute
  '/quiz': typeof QuizRoute
  '/short-notes': typeof ShortNotesRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/flash-cards': typeof AdminFlashCardsRoute
  '/admin/mcq': typeof AdminMcqRoute
  '/admin/mock-test': typeof AdminMockTestRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/question-bank': typeof AdminQuestionBankRoute
  '/admin/quiz': typeof AdminQuizRoute
  '/admin/short-notes': typeof AdminShortNotesRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/classes': typeof ClassesRoute
  '/custom-exam': typeof CustomExamRoute
  '/dashboard': typeof DashboardRoute
  '/flash-cards': typeof FlashCardsRoute
  '/mcq-practice': typeof McqPracticeRoute
  '/mock-test': typeof MockTestRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/qns-bank': typeof QnsBankRoute
  '/quiz': typeof QuizRoute
  '/short-notes': typeof ShortNotesRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/flash-cards': typeof AdminFlashCardsRoute
  '/admin/mcq': typeof AdminMcqRoute
  '/admin/mock-test': typeof AdminMockTestRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/question-bank': typeof AdminQuestionBankRoute
  '/admin/quiz': typeof AdminQuizRoute
  '/admin/short-notes': typeof AdminShortNotesRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/classes': typeof ClassesRoute
  '/custom-exam': typeof CustomExamRoute
  '/dashboard': typeof DashboardRoute
  '/flash-cards': typeof FlashCardsRoute
  '/mcq-practice': typeof McqPracticeRoute
  '/mock-test': typeof MockTestRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/qns-bank': typeof QnsBankRoute
  '/quiz': typeof QuizRoute
  '/short-notes': typeof ShortNotesRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/flash-cards': typeof AdminFlashCardsRoute
  '/admin/mcq': typeof AdminMcqRoute
  '/admin/mock-test': typeof AdminMockTestRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/question-bank': typeof AdminQuestionBankRoute
  '/admin/quiz': typeof AdminQuizRoute
  '/admin/short-notes': typeof AdminShortNotesRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/classes'
    | '/custom-exam'
    | '/dashboard'
    | '/flash-cards'
    | '/mcq-practice'
    | '/mock-test'
    | '/notifications'
    | '/profile'
    | '/qns-bank'
    | '/quiz'
    | '/short-notes'
    | '/admin/classes'
    | '/admin/flash-cards'
    | '/admin/mcq'
    | '/admin/mock-test'
    | '/admin/notifications'
    | '/admin/question-bank'
    | '/admin/quiz'
    | '/admin/short-notes'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/classes'
    | '/custom-exam'
    | '/dashboard'
    | '/flash-cards'
    | '/mcq-practice'
    | '/mock-test'
    | '/notifications'
    | '/profile'
    | '/qns-bank'
    | '/quiz'
    | '/short-notes'
    | '/admin/classes'
    | '/admin/flash-cards'
    | '/admin/mcq'
    | '/admin/mock-test'
    | '/admin/notifications'
    | '/admin/question-bank'
    | '/admin/quiz'
    | '/admin/short-notes'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/classes'
    | '/custom-exam'
    | '/dashboard'
    | '/flash-cards'
    | '/mcq-practice'
    | '/mock-test'
    | '/notifications'
    | '/profile'
    | '/qns-bank'
    | '/quiz'
    | '/short-notes'
    | '/admin/classes'
    | '/admin/flash-cards'
    | '/admin/mcq'
    | '/admin/mock-test'
    | '/admin/notifications'
    | '/admin/question-bank'
    | '/admin/quiz'
    | '/admin/short-notes'
    | '/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClassesRoute: typeof ClassesRoute
  CustomExamRoute: typeof CustomExamRoute
  DashboardRoute: typeof DashboardRoute
  FlashCardsRoute: typeof FlashCardsRoute
  McqPracticeRoute: typeof McqPracticeRoute
  MockTestRoute: typeof MockTestRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  QnsBankRoute: typeof QnsBankRoute
  QuizRoute: typeof QuizRoute
  ShortNotesRoute: typeof ShortNotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/short-notes': {
      id: '/short-notes'
      path: '/short-notes'
      fullPath: '/short-notes'
      preLoaderRoute: typeof ShortNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qns-bank': {
      id: '/qns-bank'
      path: '/qns-bank'
      fullPath: '/qns-bank'
      preLoaderRoute: typeof QnsBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-test': {
      id: '/mock-test'
      path: '/mock-test'
      fullPath: '/mock-test'
      preLoaderRoute: typeof MockTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcq-practice': {
      id: '/mcq-practice'
      path: '/mcq-practice'
      fullPath: '/mcq-practice'
      preLoaderRoute: typeof McqPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flash-cards': {
      id: '/flash-cards'
      path: '/flash-cards'
      fullPath: '/flash-cards'
      preLoaderRoute: typeof FlashCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-exam': {
      id: '/custom-exam'
      path: '/custom-exam'
      fullPath: '/custom-exam'
      preLoaderRoute: typeof CustomExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/short-notes': {
      id: '/admin/short-notes'
      path: '/short-notes'
      fullPath: '/admin/short-notes'
      preLoaderRoute: typeof AdminShortNotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quiz': {
      id: '/admin/quiz'
      path: '/quiz'
      fullPath: '/admin/quiz'
      preLoaderRoute: typeof AdminQuizRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/question-bank': {
      id: '/admin/question-bank'
      path: '/question-bank'
      fullPath: '/admin/question-bank'
      preLoaderRoute: typeof AdminQuestionBankRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mock-test': {
      id: '/admin/mock-test'
      path: '/mock-test'
      fullPath: '/admin/mock-test'
      preLoaderRoute: typeof AdminMockTestRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mcq': {
      id: '/admin/mcq'
      path: '/mcq'
      fullPath: '/admin/mcq'
      preLoaderRoute: typeof AdminMcqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flash-cards': {
      id: '/admin/flash-cards'
      path: '/flash-cards'
      fullPath: '/admin/flash-cards'
      preLoaderRoute: typeof AdminFlashCardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminClassesRoute: typeof AdminClassesRoute
  AdminFlashCardsRoute: typeof AdminFlashCardsRoute
  AdminMcqRoute: typeof AdminMcqRoute
  AdminMockTestRoute: typeof AdminMockTestRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminQuestionBankRoute: typeof AdminQuestionBankRoute
  AdminQuizRoute: typeof AdminQuizRoute
  AdminShortNotesRoute: typeof AdminShortNotesRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClassesRoute: AdminClassesRoute,
  AdminFlashCardsRoute: AdminFlashCardsRoute,
  AdminMcqRoute: AdminMcqRoute,
  AdminMockTestRoute: AdminMockTestRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminQuestionBankRoute: AdminQuestionBankRoute,
  AdminQuizRoute: AdminQuizRoute,
  AdminShortNotesRoute: AdminShortNotesRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClassesRoute: ClassesRoute,
  CustomExamRoute: CustomExamRoute,
  DashboardRoute: DashboardRoute,
  FlashCardsRoute: FlashCardsRoute,
  McqPracticeRoute: McqPracticeRoute,
  MockTestRoute: MockTestRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  QnsBankRoute: QnsBankRoute,
  QuizRoute: QuizRoute,
  ShortNotesRoute: ShortNotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
