// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function makeStubClient() {
  const noop = () => ({ data: { subscription: { unsubscribe: () => {} } } });
  const emptyQuery = () => {
    const q: Record<string, unknown> = {};
    const chain = new Proxy(q, {
      get(_, prop) {
        if (prop === 'then') return undefined;
        if (prop === 'maybeSingle' || prop === 'single') {
          return () => Promise.resolve({ data: null, error: null });
        }
        return () => {
          if (prop === 'select' || prop === 'eq' || prop === 'neq' || prop === 'in' || prop === 'order' || prop === 'limit') {
            return chain;
          }
          return Promise.resolve({ data: [], error: null });
        };
      },
    });
    return chain;
  };

  return {
    auth: {
      getSession: async () => ({ data: { session: null }, error: null }),
      signInWithPassword: async () => ({ data: null, error: { message: 'No Supabase configured. Use demo login.' } }),
      signUp: async () => ({ data: null, error: { message: 'No Supabase configured. Use demo login.' } }),
      signOut: async () => ({ error: null }),
      onAuthStateChange: noop,
      resetPasswordForEmail: async () => ({ error: null }),
      updateUser: async () => ({ data: null, error: null }),
      signInWithOAuth: async () => ({ data: null, error: { message: 'OAuth not available in demo mode.' } }),
    },
    from: () => emptyQuery(),
  } as unknown as ReturnType<typeof createSupabaseClient>;
}

function createSupabaseClient() {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    return makeStubClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
